# Generated by Django 4.1.2 on 2023-04-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='public')),
                ('videos', models.FileField(upload_to='videos/')),
                ('Date_Evenement', models.DateField()),
                ('Evenement_payant', models.BooleanField(default=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
    ]
