# Generated by Django 4.1.2 on 2023-04-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sites',
            old_name='list',
            new_name='category',
        ),
    ]
