# Generated by Django 4.1.2 on 2023-04-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_rename_list_sites_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sites',
            old_name='category',
            new_name='categorie',
        ),
    ]
