# Generated by Django 4.1.2 on 2023-04-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_rename_category_sites_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localguide',
            name='disponibilite',
        ),
    ]
