# Generated by Django 4.1.2 on 2023-04-30 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0004_remove_localguide_disponibilite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentaire',
            new_name='CommentaireSite',
        ),
    ]
